name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      HAVE_DOCKERHUB_SECRET: ${{ secrets.ALI_DOCKER_HUB_PWD != '' && secrets.ALI_DOCKER_HUB_USN != '' }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_HUB_USN }}
          password: ${{ secrets.ALI_DOCKER_HUB_PWD }}
      -
        name: Build and push geth
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/jiaxing_mss/prysm:v3.1.1